site_name: smartsettings
site_description: Smart Settings
site_author: Quan Lin

repo_url: https://github.com/jacklinquan/smartsettings
edit_uri: ""

theme:
    name: readthedocs

docs_dir: md_docs

site_dir: docs

nav:
    - Home: index.md
    - API Documentation: api.md

copyright: Copyright &copy; 2024 <a href="https://github.com/jacklinquan">Quan Lin</a>.

plugins:
    - search
    - mkapi
